title: Minimalistic
logo: /assets/img/logo.jpg
email: person@address.com
description: Minimalistic is a theme powered by Jekyll.
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/vaibhavvikas
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/vaibhavvikas

navigation:
  - name: Portfolio
    link: ./index.html
    sublist:
      - name: Recommender System
        link: ./index.html#recommender-system
      - name: Natural Language Processing
        link: ./index.html#natural-language-processing
      - name: Computer Vision
        link: ./index.html#computer-vision
      - name: Business Intelligence & Data Engineering & Big Data
        link: ./index.html#business-intelligence-&-data-engineering-&-big-data
      - name: Machine Learning
        link: ./index.html#machine-learning
      - name: Web App
        link: ./index.html#web-app
      - name: Economics
        link: ./index.html#economics
  - name: Another Page
    link: ./another-page.html
